- hosts: sandbox
  become: yes
  become_user: root
  roles:
    - hostname
    - unix_groups
    - unix_users
    - httpd
    - { role: sudoers/allow-all, group_name: group_a }
    - { role: sudoers/allow-httpd, group_name: group_b }
    - jenkins
    - cron/check_dir